db:
  synchronize: false

jwt:
  secret: 'mySecretKey'

flask:
  url: 'kdt-ai-9-team01.elicecoding.com'

domain:
  address: 'kdt-ai-9-team01.elicecoding.com'

redis:
  url: 'kdt-ai-9-team01.elicecoding.com'
